### PR TITLE
PSR4

### PR DESCRIPTION
**Pull request by Kaik**
Refactor module to psr4 #284

### CODE REVIEW

**Comment by Kaik** [comment]
I have tested this and it installs properly and most of the functionality works without errors.
I think version could be updated because it is quite a big change.
In next step I will refactor from php version file to composer. Then I will try to refactor admin controller to Twig and Symfony forms.

**Comment by craigh** [comment]
> I think version could be updated because it is quite a big change.

add this to this PR and then we will merge this. then proceed to next steps.

**Comment by Guite** [comment]
:+1:

**Comment by Kaik** [comment]
Changing version trace

line 145 is 
```
$newVersion = \Zikula\ExtensionsModule\Util::getVersionMeta($extension->getName())->getVersion();
```

```
Error: Call to a member function getVersion() on array

500 Internal Server Error - FatalErrorException

Stack Trace

in system/ExtensionsModule/Helper/ExtensionHelper.php at line 145   -
        $newVersion = $bundle->getMetaData()->getVersion();
        if (empty($newVersion)) {
            // @todo remove this legacy at Core-2.0
            $newVersion = \Zikula\ExtensionsModule\Util::getVersionMeta($extension->getName())->getVersion();
        }
        $extension->setVersion($newVersion);
at ExtensionHelper ->upgrade () 
in system/ExtensionsModule/Controller/ModuleController.php at line 359   +
at ModuleController ->upgradeAction () 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 144   +
at call_user_func_array:{/home/Kaik/public_html/dizkusdev/src/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:144} () 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 144   +
at HttpKernel ->handleRaw () 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 64   +
at HttpKernel ->handle () 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php at line 69   +
at ContainerAwareHttpKernel ->handle () 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php at line 185   +
at Kernel ->handle () 
in index.php at line 23   +
at {main} ()
Logs   -

1 error
DEBUG - Notified event "doctrine.configure" to listener "Zikula\Bundle\CoreBundle\EventListener\Doctrine1ConnectorListener::configureDoctrine".
DEBUG - Notified event "doctrine.cache" to listener "Zikula\Bundle\CoreBundle\EventListener\Doctrine1ConnectorListener::configureCache".
DEBUG - Notified event "doctrine.configure" to listener "Zikula\Bundle\CoreBundle\EventListener\Doctrine1ConnectorListener::configureDoctrine".
DEBUG - Notified event "doctrine.init_connection" to listener "Zikula\Bundle\CoreBundle\EventListener\Doctrine1ConnectorListener::doctrineInit".
DEBUG - Notified event "doctrine.boot" to listener "Zikula\Bundle\CoreBundle\EventListener\DoctrineListener::initDoctrine".
DEBUG - Notified event "core.preinit" to listener "SystemListeners::initDB".
DEBUG - SET NAMES utf8
DEBUG - SELECT value FROM module_vars WHERE modname = 'ZConfig' AND name = 'Version_Num'
DEBUG - Notified event "core.init" to listener "Zikula\Bundle\CoreInstallerBundle\EventListener\InstallUpgradeCheckListener::onCoreInit".
DEBUG - Notified event "core.init" to listener "SystemListeners::sessionLogging".
DEBUG - Notified event "core.init" to listener "SystemListeners::systemPlugins".
DEBUG - Notified event "core.init" to listener "SystemListeners::setupAutoloaderForGeneratedCategoryModels".
DEBUG - Notified event "core.init" to listener "SystemListeners::setupCsfrProtection".
DEBUG - SELECT value FROM module_vars WHERE modname = 'ZConfig' AND name = 'Version_Num'
DEBUG - Notified event "core.init" to listener "Zikula\Bundle\CoreInstallerBundle\EventListener\InstallUpgradeCheckListener::onCoreInit".
DEBUG - Notified event "core.init" to listener "SystemListeners::sessionLogging".
DEBUG - Notified event "core.init" to listener "SystemListeners::systemPlugins".
DEBUG - Notified event "core.init" to listener "SystemListeners::setupAutoloaderForGeneratedCategoryModels".
DEBUG - Notified event "core.init" to listener "SystemListeners::setupCsfrProtection".
DEBUG - SELECT t0.id AS id_1, t0.modname AS modname_2, t0.name AS name_3, t0.value AS value_4 FROM module_vars t0
DEBUG - SELECT t0.id AS id_1, t0.name AS name_2, t0.type AS type_3, t0.displayname AS displayname_4, t0.url AS url_5, t0.description AS description_6, t0.directory AS directory_7, t0.version AS version_8, t0.capabilities AS capabilities_9, t0.state AS state_10, t0.securityschema AS securityschema_11, t0.core_min AS core_min_12, t0.core_max AS core_max_13 FROM modules t0
DEBUG - SELECT value FROM module_vars WHERE modname = 'ZConfig' AND name = 'Version_Num'
DEBUG - Notified event "core.init" to listener "Zikula\Bundle\CoreInstallerBundle\EventListener\InstallUpgradeCheckListener::onCoreInit".
DEBUG - Notified event "core.init" to listener "SystemListeners::sessionLogging".
DEBUG - Notified event "core.init" to listener "SystemListeners::systemPlugins".
DEBUG - Notified event "core.init" to listener "SystemListeners::setupAutoloaderForGeneratedCategoryModels".
DEBUG - Notified event "core.init" to listener "SystemListeners::setupCsfrProtection".
DEBUG - SELECT value FROM module_vars WHERE modname = 'ZConfig' AND name = 'Version_Num'
DEBUG - Notified event "core.init" to listener "Zikula\Bundle\CoreInstallerBundle\EventListener\InstallUpgradeCheckListener::onCoreInit".
DEBUG - Notified event "core.init" to listener "SystemListeners::sessionLogging".
DEBUG - Notified event "core.init" to listener "SystemListeners::systemPlugins".
DEBUG - Notified event "core.init" to listener "SystemListeners::setupAutoloaderForGeneratedCategoryModels".
DEBUG - Notified event "core.init" to listener "SystemListeners::setupCsfrProtection".
DEBUG - SELECT value FROM module_vars WHERE modname = 'ZConfig' AND name = 'Version_Num'
DEBUG - Notified event "core.init" to listener "Zikula\Bundle\CoreInstallerBundle\EventListener\InstallUpgradeCheckListener::onCoreInit".
DEBUG - Notified event "core.init" to listener "SystemListeners::sessionLogging".
DEBUG - Notified event "core.init" to listener "SystemListeners::systemPlugins".
DEBUG - Notified event "core.init" to listener "SystemListeners::setupAutoloaderForGeneratedCategoryModels".
DEBUG - Notified event "core.init" to listener "SystemListeners::setupCsfrProtection".
DEBUG - SELECT value FROM module_vars WHERE modname = 'ZConfig' AND name = 'Version_Num'
DEBUG - Notified event "core.init" to listener "Zikula\Bundle\CoreInstallerBundle\EventListener\InstallUpgradeCheckListener::onCoreInit".
DEBUG - Notified event "core.init" to listener "SystemListeners::sessionLogging".
DEBUG - Notified event "core.init" to listener "SystemListeners::systemPlugins".
DEBUG - Notified event "core.init" to listener "SystemListeners::setupAutoloaderForGeneratedCategoryModels".
DEBUG - Notified event "core.init" to listener "SystemListeners::setupCsfrProtection".
DEBUG - SELECT t0.id AS id_1, t0.name AS name_2, t0.type AS type_3, t0.displayname AS displayname_4, t0.description AS description_5, t0.directory AS directory_6, t0.version AS version_7, t0.contact AS contact_8, t0.admin AS admin_9, t0.user AS user_10, t0.system AS system_11, t0.state AS state_12, t0.xhtml AS xhtml_13 FROM themes t0
DEBUG - SELECT t0.uid AS uid_1, t0.uname AS uname_2, t0.email AS email_3, t0.pass AS pass_4, t0.passreminder AS passreminder_5, t0.activated AS activated_6, t0.approved_date AS approved_date_7, t0.approved_by AS approved_by_8, t0.user_regdate AS user_regdate_9, t0.lastlogin AS lastlogin_10, t0.theme AS theme_11, t0.tz AS tz_12, t0.locale AS locale_13 FROM users t0 WHERE t0.uid IN (?)
DEBUG - SELECT g0_.pid AS pid_0, g0_.gid AS gid_1, g0_.sequence AS sequence_2, g0_.realm AS realm_3, g0_.component AS component_4, g0_.instance AS instance_5, g0_.level AS level_6, g0_.bond AS bond_7 FROM group_perms g0_ WHERE g0_.gid IN (?) ORDER BY g0_.sequence ASC
DEBUG - SELECT value FROM module_vars WHERE modname = 'ZConfig' AND name = 'Version_Num'
DEBUG - Notified event "core.init" to listener "Zikula\Bundle\CoreInstallerBundle\EventListener\InstallUpgradeCheckListener::onCoreInit".
DEBUG - Notified event "core.init" to listener "SystemListeners::sessionLogging".
DEBUG - Notified event "core.init" to listener "SystemListeners::systemPlugins".
DEBUG - Notified event "core.init" to listener "SystemListeners::setupAutoloaderForGeneratedCategoryModels".
DEBUG - Notified event "core.init" to listener "SystemListeners::setupCsfrProtection".
DEBUG - SELECT value FROM module_vars WHERE modname = 'ZConfig' AND name = 'Version_Num'
DEBUG - Notified event "core.init" to listener "Zikula\Bundle\CoreInstallerBundle\EventListener\InstallUpgradeCheckListener::onCoreInit".
DEBUG - Notified event "core.init" to listener "SystemListeners::sessionLogging".
DEBUG - Notified event "core.init" to listener "SystemListeners::systemPlugins".
DEBUG - Notified event "core.init" to listener "SystemListeners::setupAutoloaderForGeneratedCategoryModels".
DEBUG - Notified event "core.init" to listener "SystemListeners::setupCsfrProtection".
DEBUG - SELECT t0.id AS id_1, t0.modname AS modname_2, t0.name AS name_3, t0.value AS value_4 FROM module_vars t0
INFO - The Symfony\Component\DependencyInjection\Definition::setScope method is deprecated since version 2.8 and will be removed in 3.0.
DEBUG - SELECT t0.uid AS uid_1, t0.uname AS uname_2, t0.email AS email_3, t0.pass AS pass_4, t0.passreminder AS passreminder_5, t0.activated AS activated_6, t0.approved_date AS approved_date_7, t0.approved_by AS approved_by_8, t0.user_regdate AS user_regdate_9, t0.lastlogin AS lastlogin_10, t0.theme AS theme_11, t0.tz AS tz_12, t0.locale AS locale_13 FROM users t0 WHERE t0.uid IN (?)
DEBUG - SELECT g0_.pid AS pid_0, g0_.gid AS gid_1, g0_.sequence AS sequence_2, g0_.realm AS realm_3, g0_.component AS component_4, g0_.instance AS instance_5, g0_.level AS level_6, g0_.bond AS bond_7 FROM group_perms g0_ WHERE g0_.gid IN (?) ORDER BY g0_.sequence ASC
INFO - Matched route "zikulaextensionsmodule_module_upgrade".
DEBUG - SELECT vars FROM session_info WHERE sessid=:id
DEBUG - SELECT t0.uid AS uid_1, t0.uname AS uname_2, t0.email AS email_3, t0.pass AS pass_4, t0.passreminder AS passreminder_5, t0.activated AS activated_6, t0.approved_date AS approved_date_7, t0.approved_by AS approved_by_8, t0.user_regdate AS user_regdate_9, t0.lastlogin AS lastlogin_10, t0.theme AS theme_11, t0.tz AS tz_12, t0.locale AS locale_13 FROM users t0 WHERE t0.uid = ? LIMIT 1
DEBUG - SELECT t0.name AS name_1, t0.value AS value_2, t0.user_id AS user_id_3 FROM users_attributes t0 WHERE t0.user_id = ?
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DumpListener::configure".
DEBUG - Notified event "kernel.request" to listener "Zikula\Bundle\CoreBundle\EventListener\OutputCompressionListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Zikula\Bundle\CoreBundle\EventListener\StripFrontControllerListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ValidateRequestListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Zikula\BlocksModule\Listener\CollapseableBlockListener::addCollapseableBehavior".
DEBUG - Notified event "kernel.request" to listener "Zikula\ThemeModule\EventListener\DefaultPageAssetSetterListener::setDefaultPageAssets".
DEBUG - Notified event "kernel.request" to listener "Zikula\ThemeModule\EventListener\DefaultPageVarSetterListener::setDefaultPageVars".
DEBUG - Notified event "kernel.request" to listener "Zikula\Bundle\CoreBundle\EventListener\SiteOffListener::onKernelRequestSiteOff".
DEBUG - Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Zikula\SecurityCenterModule\Listener\FilterListener::idsInputFilter".
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\FragmentListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Zikula\SearchModule\Listener\FrontControllerListener::pageLoad".
DEBUG - Notified event "kernel.request" to listener "Zikula\Bundle\CoreBundle\EventListener\RouterListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Zikula\Bundle\CoreBundle\EventListener\SessionExpireListener::onKernelRequestSessionExpire".
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\TranslatorListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Stof\DoctrineExtensionsBundle\EventListener\LocaleListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Stof\DoctrineExtensionsBundle\EventListener\LoggerListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Zikula\Bundle\CoreBundle\EventListener\BlameListener::onKernelRequest".
DEBUG - Notified event "kernel.controller" to listener "Symfony\Bundle\FrameworkBundle\DataCollector\RouterDataCollector::onKernelController".
DEBUG - Notified event "kernel.controller" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelController".
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController".
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController".
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelController".
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener::onKernelController".
DEBUG - Notified event "kernel.controller" to listener "Zikula\ThemeModule\EventListener\ControllerAnnotationReaderListener::readControllerAnnotations".
DEBUG - Notified event "kernel.controller" to listener "Zikula\ThemeModule\EventListener\TemplatePathOverrideListener::setUpThemePathOverrides".
DEBUG - Notified event "kernel.controller" to listener "Zikula\ThemeModule\EventListener\ModuleStylesheetInsertListener::insertModuleStylesheet".
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController".
DEBUG - SELECT t0.uid AS uid_1, t0.uname AS uname_2, t0.email AS email_3, t0.pass AS pass_4, t0.passreminder AS passreminder_5, t0.activated AS activated_6, t0.approved_date AS approved_date_7, t0.approved_by AS approved_by_8, t0.user_regdate AS user_regdate_9, t0.lastlogin AS lastlogin_10, t0.theme AS theme_11, t0.tz AS tz_12, t0.locale AS locale_13 FROM users t0 WHERE t0.uid IN (?)
DEBUG - SELECT t0.gid AS gid_1, t0.name AS name_2, t0.gtype AS gtype_3, t0.description AS description_4, t0.prefix AS prefix_5, t0.state AS state_6, t0.nbuser AS nbuser_7, t0.nbumax AS nbumax_8, t0.link AS link_9, t0.uidmaster AS uidmaster_10 FROM groups t0 INNER JOIN group_membership ON t0.gid = group_membership.gid WHERE group_membership.uid = ?
DEBUG - SELECT g0_.pid AS pid_0, g0_.gid AS gid_1, g0_.sequence AS sequence_2, g0_.realm AS realm_3, g0_.component AS component_4, g0_.instance AS instance_5, g0_.level AS level_6, g0_.bond AS bond_7 FROM group_perms g0_ WHERE g0_.gid IN (?) ORDER BY g0_.sequence ASC
CRITICAL - Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function getVersion() on array" at /home/Kaik/public_html/dizkusdev/src/system/ExtensionsModule/Helper/ExtensionHelper.php line 145
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DumpListener::configure".
DEBUG - Notified event "kernel.request" to listener "Zikula\Bundle\CoreBundle\EventListener\OutputCompressionListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Zikula\Bundle\CoreBundle\EventListener\StripFrontControllerListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ValidateRequestListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Zikula\BlocksModule\Listener\CollapseableBlockListener::addCollapseableBehavior".
DEBUG - Notified event "kernel.request" to listener "Zikula\ThemeModule\EventListener\DefaultPageAssetSetterListener::setDefaultPageAssets".
DEBUG - Notified event "kernel.request" to listener "Zikula\ThemeModule\EventListener\DefaultPageVarSetterListener::setDefaultPageVars".
DEBUG - Notified event "kernel.request" to listener "Zikula\Bundle\CoreBundle\EventListener\SiteOffListener::onKernelRequestSiteOff".
DEBUG - Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Zikula\SecurityCenterModule\Listener\FilterListener::idsInputFilter".
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\FragmentListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Zikula\SearchModule\Listener\FrontControllerListener::pageLoad".
DEBUG - Notified event "kernel.request" to listener "Zikula\Bundle\CoreBundle\EventListener\RouterListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Zikula\Bundle\CoreBundle\EventListener\SessionExpireListener::onKernelRequestSessionExpire".
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\TranslatorListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Stof\DoctrineExtensionsBundle\EventListener\LocaleListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Stof\DoctrineExtensionsBundle\EventListener\LoggerListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Zikula\Bundle\CoreBundle\EventListener\BlameListener::onKernelRequest".
DEBUG - Notified event "kernel.controller" to listener "Symfony\Bundle\FrameworkBundle\DataCollector\RouterDataCollector::onKernelController".
DEBUG - Notified event "kernel.controller" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelController".
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController".
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController".
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelController".
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener::onKernelController".
DEBUG - Notified event "kernel.controller" to listener "Zikula\ThemeModule\EventListener\ControllerAnnotationReaderListener::readControllerAnnotations".
DEBUG - Notified event "kernel.controller" to listener "Zikula\ThemeModule\EventListener\TemplatePathOverrideListener::setUpThemePathOverrides".
DEBUG - Notified event "kernel.controller" to listener "Zikula\ThemeModule\EventListener\ModuleStylesheetInsertListener::insertModuleStylesheet".
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController".
Stack Trace (Plain Text)   -

[1] Symfony\Component\Debug\Exception\FatalErrorException: Error: Call to a member function getVersion() on array
    at n/a
        in /home/Kaik/public_html/dizkusdev/src/system/ExtensionsModule/Helper/ExtensionHelper.php line 145

    at Zikula\ExtensionsModule\Helper\ExtensionHelper->upgrade()
        in /home/Kaik/public_html/dizkusdev/src/system/ExtensionsModule/Controller/ModuleController.php line 359

    at Zikula\ExtensionsModule\Controller\ModuleController->upgradeAction()
        in /home/Kaik/public_html/dizkusdev/src/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 144

    at call_user_func_array:{/home/Kaik/public_html/dizkusdev/src/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:144}()
        in /home/Kaik/public_html/dizkusdev/src/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 144

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
        in /home/Kaik/public_html/dizkusdev/src/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 64

    at Symfony\Component\HttpKernel\HttpKernel->handle()
        in /home/Kaik/public_html/dizkusdev/src/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php line 69

    at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle()
        in /home/Kaik/public_html/dizkusdev/src/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 185

    at Symfony\Component\HttpKernel\Kernel->handle()
        in /home/Kaik/public_html/dizkusdev/src/index.php line 23

    at {main}()
        in /home/Kaik/public_html/dizkusdev/src/index.php line 0
```

**Comment by Kaik** [comment]
Ok this is mostly done there are few things with an upgrade that I do not know how to refactor. Module upgrade from 4.0.0, uninstall and install works.

**Comment by Kaik** [comment]
hmm something is wrong...

**Comment by craigh** [comment]
The prefix thing is _intended_ to fail.
It was designed to upgrade from 3.1 tables which included the prefix. I think the README says something about it.

**Comment by craigh** [comment]
> Please check if everything looks good before merge.

too big to really look over. I'll just merge it. If it breaks, then you'll fix it 👍

**Pull request merged**
