### PR TITLE
Merge v5 into master

### PR DESCRIPTION
**Pull request by Kaik**
To check do not merge

### CODE REVIEW

**Comment by Kaik** [comment]
@craigh could you please check if this is ok? I have worked on v5 (which is for core 1.5) and I want to update master with new code, but it does not look good to me at least not clear. Commits that are here are already in master.

**Comment by Kaik** [comment]
I will merge it and see what happens.

**Comment by craigh** [comment]
sorry - I didn't get this message until now.

**Comment by Kaik** [comment]
no problem - I have found out that something is wrong with it :( need to reverse it and see what can be done... for some reason things are duplicated https://github.com/zikula-modules/DizkusModule/blob/master/Entity/ForumEntity.php#L328
https://github.com/zikula-modules/DizkusModule/blob/master/Entity/ForumEntity.php#L363

I think it is because I have changed git procedure (the way I manage branches) to have a similar situation as it is in the core (git workflow, the way you are managing multiple versions) and I did something wrong, and now I need to find out how to fix it...

**Comment by Kaik** [comment]
@craigh If you have any idea how can I fix it or at least what is wrong would be great.

**Comment by craigh** [comment]
I'm sorry I don't have any idea. In the end though, the git history is only valuable to the developer. If the codebase is where you want it, I would leave it. Spend your time coding, not fixing git.

**Pull request merged**
