### PR TITLE
V4 hooks

### PR DESCRIPTION
**Pull request by Kaik**
Base topic provider and hook settings.
#300 #316

### CODE REVIEW

**Comment by craigh** [comment]
I've hope you've read this: https://github.com/zikula/core/tree/master/src/docs/Hooks

specifically this: https://github.com/zikula/core/blob/master/src/docs/Hooks/2.TaggedHookServices.md

regarding "Tagged Hook Services" and not using persisted hooks.

**Comment by Kaik** [comment]
Well, yes I'm aware of those changes this is:
1. Zikula 1.4.x version should work on 1.5
2. I will go into this again for core 2.0 I expect some things to change.

**Comment by craigh** [comment]
you can merge however you like. it is only a timeline difference. 

my point was that if you are into now, you should make the changes now unless you are working for 1.4 compatibility

**Comment by Kaik** [comment]
Yes this is 1.4 for 2.0 it would be easier to do this :) anyway this one will stay for 1.4 I will try to merge it with version for 2.0 and then update to new but first I need to finish hooks import, then forum moderation and all missing stuff for 1.4/1.5... then I will move to 2.0 and new features.

**Comment by Kaik** [comment]
It might fail on install/upgrade I'm working on this now.

**Pull request merged**
